version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Vivekkumar-IN/EditguardianBot"
  cgo_enabled = false

[[transformers]]
name = "gofmt"


[[transformers]]
name = "gofumpt"