name: Go Init Check

on:
  push:
    paths:
      - "**.go"
      - "**.yml"
  workflow_dispatch:

jobs:
  init-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Initialize Go Module
      run: |
        go mod init github.com/Vivekkumar-IN/EditguardianBot
        go get github.com/PaulSonOfLars/gotgbot/v2
        #go mod tidy

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Initialize Go module and add dependencies"
        commit_options: "--no-verify"
        repository: .
        commit_user_name: "github-actions[bot]"
        commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
        commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"